### ISSUE TITLE
Criação de services

### ISSUE THREAD

**Issue by Dihgg** [MeConta/me-conta-backend#11]
Precisamos criar os services para atender o CRUD padrão

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Formulário de contato](https://trello.com/c/vBqcPsLi/12-formul%C3%A1rio-de-contato)

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Realizar cadastro de atendente](https://trello.com/c/VafQanKt/73-realizar-cadastro-de-atendente)

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visualizar o perfil do atendente como visitante](https://trello.com/c/vbEtdA8Y/70-visualizar-o-perfil-do-atendente-como-visitante)

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visualizar o perfil do atendente como aluno](https://trello.com/c/5I9GEp8H/72-visualizar-o-perfil-do-atendente-como-aluno)

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Visualizar o perfil do atendente como supervisor](https://trello.com/c/oGZ5ueBC/71-visualizar-o-perfil-do-atendente-como-supervisor)

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Realizar cadastro de aluno](https://trello.com/c/zvVraUow/83-realizar-cadastro-de-aluno)

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Listagem de atendentes da landing page](https://trello.com/c/JoGuUgd9/13-listagem-de-atendentes-da-landing-page)

**Comment by temonteiro** [comment]
- [ ] Usuário
- [ ] Frente de atuação
- [ ] Atendente
- [ ] Aluno
- [ ] Supervisor
- [ ] Contato
- [ ] Agenda
- [ ] Avaliação
- [ ] Consulta

**Comment by Dihgg** [comment]
Vamos pegar os services elencado pela @temonteiro para terminar e re-validar as regras de negócio

**Comment by Dihgg** [comment]
Terminamos de criar o CRUD padrão para todas as entidades, agora precisamos validar e ajustar regras de negócio

**Comment by Dihgg** [comment]
- [ ] Limitação máxima de página
- [ ] queries de paginação não aparecem no swagger
