### ISSUE TITLE
Adição do TypeORM

### ISSUE THREAD

**Issue by Dihgg** [MeConta/me-conta-backend#2]
Precisamos adicionar o [TypeORM](https://docs.nestjs.com/recipes/sql-typeorm) ao projeto

**Comment by temonteiro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adição do TypeORM](https://trello.com/c/1DyZ7XEz/46-adi%C3%A7%C3%A3o-do-typeorm)
