### ISSUE TITLE
Criação de Atendente retorna erro 422 "Usuário já cadastrado" para novos usuários

### ISSUE THREAD

**Issue by nelizasilva** [MeConta/me-conta-backend#26]
**Passos:**

1. Abra o Swagger de Atendente para o serviço POST: https://me-conta-backend.herokuapp.com/api/#/
2. Adicione o request abaixo (mude o email para um novo se preferir) e execute.
``` json
{
  "senha": "s#nh4Valida",
  "dataNascimento": "1988-03-09",
  "telefone": "(81) 91234-5678",
  "email": "testeMariaClara@teste.com",
  "frentesAtuacao": [
    1
  ],
  "nome": "MariaClara Silva",
  "genero": "F",
  "UF": "AC",
  "cidade": "Acrelândia",
  "descricao": "teste",
  "instituicao": "teste",
  "formado": true,
  "anoConclusao": 2010,
  "especializacao": "teste",
  "crp": "string",
  "semestre": 10
}
```

**Comportamento atual**
Ao cadastrar o usuário no POST do Swagger de Atendente, ocorre o erro 422 "Usuário já cadastrado" para novos usuários com e-mails que não foram utilizados ainda. 
Se utilizar o GET para verificar os Atendentes já cadastrados, não retorna nenhum atendente. Isso prova que realmente não existe outro registro com o mesmo e-mail e ele poderia ser cadastrado com sucesso.

**Resultado esperado**
Deve ser possível cadastrar um novo usuário com e-mail ainda não utilizado.

**Comment by Dihgg** [comment]
O problema era falta de variáveis de ambiente na aplicação do HEROKU
