### ISSUE TITLE
Adição do Swagger

### ISSUE THREAD

**Issue by Dihgg** [MeConta/me-conta-backend#3]
Precisamos adicionar o [swagger](https://docs.nestjs.com/openapi/introduction) a aplicação

**Comment by temonteiro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adição do Swagger](https://trello.com/c/dWNDUN7G/47-adi%C3%A7%C3%A3o-do-swagger)

**Comment by Dihgg** [comment]
- [ ] Usuário
- [ ] Frente de atuação
- [ ] Atendente
- [ ] Aluno
- [ ] Supervisor
- [ ] Contato
- [ ] Agenda
- [ ] Avaliação
- [ ] Consulta

**Comment by Dihgg** [comment]
- [ ] Payload do atendente está incorreto

**Comment by Dihgg** [comment]
Reaberto pois há ajustes de payload do atendente
