### ISSUE TITLE
Atualização de perfil de Alunos

### ISSUE THREAD

**Issue by Dihgg** [MeConta/me-conta-backend#40]
Devemos criar os endpoints para atualização de perfil do aluno

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [perfil aluna](https://trello.com/c/UKhpFBcy/45-perfil-aluna)

**Comment by alexandreramires** [comment]
Revisamos o código-fonte, e o/a aluno/a pode atualizar. 
O endpoint `/aluno/atualizar` .
