### ISSUE TITLE
Revisar o modelo de dados

### ISSUE THREAD

**Issue by temonteiro** [MeConta/me-conta-backend#6]
Revisar se o modelo que foi feito está contemplando as mudanças que foram informadas pela PO na conversa de sexta (06/07/21).

**Comment by Dihgg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revisar o modelo de dados](https://trello.com/c/XS2MQO4b/51-revisar-o-modelo-de-dados)

**Comment by temonteiro** [comment]
Revisado no dia 10/08.
